### ISSUE TITLE
no such column: students_student.student_number

### ISSUE THREAD

**Issue by speedforce-lk** [BobsProgrammingAcademy/student-management-system#2]
![image](https://github.com/BobsProgrammingAcademy/student-management-system/assets/122682099/8ebe4e33-d068-427a-9dad-9c0531951931)

**Comment by BobsProgrammingAcademy** [comment]
Can you please explain the problem in detail and describe the **steps to reproduce it**? Be as detailed as possible.

Also, have you tried to compare your code with the code in the project's GitHub repository? If you can't see the difference by comparing the files (the error in your code might be something small and easily missed), then copying the code from the project's GitHub repository could fix the issue. Please let us know if copying the code fixed your issue.

**Comment by BobsProgrammingAcademy** [comment]
I am closing this issue as no explanation or reproduction steps were provided.
